#!/bin/bash
# vim: set ft=sh

set -e -x

go get -t -v ./...

## Lock down etcd since latest code is very broken
## See: https://github.com/coreos/etcd/issues/986
export first_gospace=$(echo $GOPATH | cut -d ':' -f 1)
mkdir -p $first_gospace/src/github.com/coreos/etcd
pushd $first_gospace/src/github.com/coreos/etcd
  git clone https://github.com/coreos/etcd.git . || true
  git checkout 0a2384bf4daec35a814244dc4d885e14f18b5ef1
  go install .
popd

go get github.com/dustin/goveralls
go get code.google.com/p/go.tools/cmd/cover
go get github.com/apcera/gnatsd
go install github.com/onsi/ginkgo/ginkgo

for gospace in $(echo $GOPATH | tr ':' ' '); do
  export PATH=$gospace/bin:$PATH
done

ginkgo -cover -r -failOnPending -randomizeAllSpecs -race -trace -skipPackage=integration "$@"
ginkgo -failOnPending -randomizeAllSpecs -trace -race integration
